### ISSUE TITLE
[Feature]: Integration between SORA wallet and fiat wallet

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card#116]
# Problem statement
Because of regulations we cannot yet integrate banking operations directly into the app (bank transfers, card freeze, changing PIN). For that reason our partners are developing a fiat wallet dedicated to those operations. 

We need to integrate the navigation between the SORA wallet and the fiat wallet. 

# Tasks
### Design

- [ ] Design

### Development
- [ ] Web

### Design
- [ ] Design

### Development
- [ ] Android
- [ ] iOS

**Comment by soracard** [comment]
duplicates https://github.com/sora-xor/sora-card/issues/123
