### ISSUE TITLE
Revise the KYC process flow

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora-card#2]
The current implementation includes crucial user scenarios, and the current functioning of most client applications is explained in the "Grudge implementation" under https://www.figma.com/file/UnGtamQIjlkxEqnsTOYoFy/SORA-Card-Logic?node-id=0-1&t=QsKXwaLrjV6zG5nM-0. The correct approach is shown on the left side under "Ideal logic" of the same diagram. Within this task, the layouts must be redesigned to allow the development team of the relevant platform to modify them.

# Steps
- [x] #4
- Implement necessary changes in applications
  - [x] https://github.com/sora-xor/sora-card-android/issues/13
  - [x] https://github.com/sora-xor/sora-card-ios/issues/9
  - [x] https://github.com/sora-xor/sora-card-web/issues/1

**Comment by spitsynval** [comment]
Here's the updated flow in Figma:
https://www.figma.com/file/Rqm3Y2XAq3pg0zfProoaqe/%F0%9F%9A%A7-SORA-Wallet-Design-WIP?node-id=0%3A1&t=w5L1Kk88b4ijocJE-1
