### ISSUE TITLE
See SORA Card IBAN Balance on Main Menu

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora-card#31]
https://www.figma.com/file/XhTyv6TrsoVXRDlO7Ud9mS/%F0%9F%94%A8-SORA-Wallet-(in-Development)?type=design&node-id=1872-10163&mode=design&t=px8T7gTKeQo5C8Zl-0

**Comment by bgodlin** [comment]
@spitsynval kindly implement the web mockups provided above.

**Comment by spitsynval** [comment]
https://www.figma.com/file/XhTyv6TrsoVXRDlO7Ud9mS/%F0%9F%94%A8-SORA-Wallet-(in-Development)?type=design&node-id=1872%3A10163&mode=design&t=CGjwKdKFNuyRMfM1-1
