### ISSUE TITLE
Buy XOR with Euro

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card#40]
<br/>

Aha! Link: https://soramitsucoltd.aha.io/features/SC-23

**Comment by bgodlin** [comment]
@Tieumsan how is this task different from X1 integration initiative?

**Comment by Tieumsan** [comment]
@bgodlin this is the integration w/ X1. Just added it to Github to have a history for phase 1 here as well. Hence the reason it is in the QA column
