### ISSUE TITLE
Fix text about 'or €20 application fee' in Localise

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora-card#55]
Actual result for rus language is:
![image](https://github.com/sora-xor/sora-card/assets/17094492/83e37e48-6b36-4dac-b522-663caa79838a)
Expected result:
Should be dynamic amount (not hardcode)
![image](https://github.com/sora-xor/sora-card/assets/17094492/bdb33f6a-28b0-4eb0-b211-19e2965f1ddc)

**Comment by Tieumsan** [comment]
@ra9mls is it the same on Android or only iOS ?

**Comment by bgodlin** [comment]
To be implemented as part of https://github.com/sora-xor/sora-card/issues/90
