### ISSUE TITLE
Display SORA Card IBAN Balance on Main Menu

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card#6]
As a <ins>SORA Card user</ins> I want to <ins>see my SORA Card balance on the main screen</ins> so that <ins>I can easily see the state of my fiat and crypto assets altogether</ins>.

# Requirements

## Backend

Implemented as part of https://github.com/soramitsu/sora-card-backend/issues/246

## Client applications

- `/ListIbans` (implemented as part of https://github.com/sora-xor/sora-card/issues/52) should be called to receive the relevant balance, no additionals calls will have to be performed. The `AvailableBalance` field should be utilized and subsequently displayed on every occasion.
- The application should automatically fetch the required data from the backend each time the screen is accessed (see request model in https://github.com/soramitsu/sora-card-backend/issues/246). 
- The application should allow the user to update the balance
  - On web platforms, the user should be able to initiate an update by performing a page reload
  - On mobile applications, the user should be able to initiate an update by utilizing the drag-and-drop functionality
- The application should store the fetched data in a cache to ensure accessibility even when offline
- The application should provide the user with the timestamp of the last data retrieval. This timestamp allows users to determine the freshness of the displayed data

### Web

- Design
  - [x] https://github.com/sora-xor/sora-card/issues/31
- Development
  - [x] https://github.com/sora-xor/sora-card-web/issues/10

### Mobile

- Design
  - [x] https://github.com/sora-xor/sora-card/issues/30
- Development
  - [x] https://github.com/sora-xor/sora-card-ios/issues/15
  - [x] https://github.com/sora-xor/sora-card-android/issues/10

Aha! Link: https://soramitsucoltd.aha.io/features/SC-9

**Comment by ra9mls** [comment]
@bgodlin could you attach right links for this design?
Display SORA Card Balance on Main Menu - this is not the same like Display SORA Card Balance on Card Hub

**Comment by bgodlin** [comment]
Duplicates #8

**Comment by Tieumsan** [comment]
> Duplicates #8

This is not a duplicate. One is about displaying the balance in the Card on the Main Menu, #8 is about displaying the balance in the SORA Card hub, as indicated by the title of the tasks.
@bgodlin

**Comment by bgodlin** [comment]
> > Duplicates #8
> 
> This is not a duplicate. One is about displaying the balance in the Card on the Main Menu, #8 is about displaying the balance in the SORA Card hub, as indicated by the title of the tasks. @bgodlin

@Tieumsan From the screens we are currently observing, am I correct in understanding that you refer to https://www.figma.com/file/XhTyv6TrsoVXRDlO7Ud9mS/%F0%9F%94%A8-SORA-Wallet-(in-Development)?type=design&node-id=1872-10425&mode=design&t=g8gT49KZhIjEPkfR-4 for the **main screen** and https://www.figma.com/file/XhTyv6TrsoVXRDlO7Ud9mS/%F0%9F%94%A8-SORA-Wallet-(in-Development)?type=design&node-id=1872-10304&mode=design&t=g8gT49KZhIjEPkfR-4 for **Card Hub screen**? 

If this is indeed the case, could you please explain the reasoning behind segmenting these tasks when they deliver equivalent business value? Moreover, considering that we might not anticipate the number of instances of the same component or number scattered throughout the project in the future, I'm uncertain about the benefits of continuing to divide features based on their location.

**Comment by Tieumsan** [comment]
@bgodlin Figma links: indeed

This is only one of the ways to split user stories. You can discuss it with the developers during the next grooming to see which task decomposition makes the most sense from the developers' perspective.
