### ISSUE TITLE
Phone number validation

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora-card#68]

**Comment by ab10001** [comment]
WEB Figma: 
https://www.figma.com/file/aDkwf6C8zmyJjudJOuuhrH/Polkaswap-v1.x.x-(Current)?type=design&node-id=16988%3A1186&mode=design&t=L6fmyfT8nMhVXML2-1

**Comment by spitsynval** [comment]
SORA Mobile:
 https://www.figma.com/file/XhTyv6TrsoVXRDlO7Ud9mS/%F0%9F%94%A8-SORA-Wallet-(in-Development)?type=design&node-id=1501%3A11483&mode=design&t=HUsTIYOeui0ku170-1
