### ISSUE TITLE
Add KYC documents link ahead of application

### ISSUE THREAD

**Issue by BenoXYZ** [sora-xor/sora-card#69]
### Problem Statement
Users experienced unclear rejection because their proof of address were not accepted by our partner.
Sumsub is currently rejecting neobank bank statements: Revolut, N26, ...
It should work if you apply with a regular commercial bank statement. We want to make sure the user is aware before starting the application process and KYC.

Documents accepted by SumSub: https://help.sumsub.com/products/supported-poa-documents#which-documents-count-as-proof-of-address

### Definition of Done
 Add the following disclaimer on the "Get SORA Card" page: 
 "You will need to provide the following documents in order to successfully pass the KYC."
 
 "the following documents" leads to a page with 
 
 Identification:
 National ID card
 Passport
 
 Proof of Address:
1) Bank statement (NOT from a neobank like Revolut or N26)
2) Utility bill for gas, electricity, water, etc. linked to the property.
3) Letters from a recognized public authority or public servant/any government-issued correspondence.
4) Current lease agreement with signatures of the landlord and the tenant.
5) Credit card statement.
6) Employer’s certificate for proof of residence.
7) House purchase deed.
*For 1) and 2), it’s common practice to reject proof of address documents older than 3 months.

 
#### Web

Design: @spitsynval 

- [x] https://github.com/sora-xor/sora-card-web/issues/25

 
#### Mobile

Design: @spitsynval 

- [x] https://github.com/sora-xor/sora-card-android/issues/95
- [x] https://github.com/sora-xor/sora-card-ios/issues/67

**Comment by bgodlin** [comment]
Duplicates https://github.com/sora-xor/sora-card/issues/69

**Comment by bgodlin** [comment]
Duplicates #63
