### ISSUE TITLE
[Bug]: GetReferenceNumber call returns the same user_reference_number

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora-card#78]
Problem statement:
GetReferenceNumber (https://kyc-test.soracard.com/Whitelabel/GetReferenceNumber) call returns the same user_reference_number for some users that started KYC process. user_reference_number is an identifier of KYC, and now one KYC attempt can change from rejected to success and it is counted as a single KYC attempt. Moreover, the user has only single KYC attempt, because there is only one user_reference_number that is used to start KYC. Overall, logic with KYC attempts is broken now
https://t.me/c/1869740055/16

**Comment by Tieumsan** [comment]
@ra9mls has this been solved or any update ?
It is not clear from the task description which platform is concerned and how we could solve the issue.
I believe this is an issue from our partners' backend.

**Comment by ra9mls** [comment]
We figured out that it was good behaviour for new Retry status. Will close it now.
