### ISSUE TITLE
Modify the Wording Displayed on Certain Screens

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora-card#79]
# Problem

Relevant screen: https://github.com/sora-xor/sora-card/issues/79#issuecomment-1699563196

1. On, the term "deposit XOR" is used. "Receive" might be a more suitable choice of wording.
2. The phrase "Buy XOR with EUR" doesn't seem accurate because regardless of the currency on one's debit/credit card, it will be converted anyway

# Solution

"Deposit XOR" -> "Receive XOR"
"Buy XOR with EUR" -> "Buy XOR with card"

# Sub-tasks

- [x] sora-xor/sora-card-android#107
- [x] sora-xor/sora-card-ios#74

**Comment by ab10001** [comment]
Mobile Figma design:
https://www.figma.com/file/XhTyv6TrsoVXRDlO7Ud9mS/%F0%9F%94%A8-SORA-Wallet-(in-Development)?type=design&node-id=1501%3A11536&mode=design&t=ypC5VihG1N0NGUyN-1

**Comment by arvifox** [comment]
> Mobile Figma design: https://www.figma.com/file/XhTyv6TrsoVXRDlO7Ud9mS/%F0%9F%94%A8-SORA-Wallet-(in-Development)?type=design&node-id=1501%3A11536&mode=design&t=ypC5VihG1N0NGUyN-1

the link leads nowhere

**Comment by arvifox** [comment]
please keep in mind that I (or any dev) change only **en** and **ru** locales.

**Comment by ra9mls** [comment]
@bgodlin please help with it. How it realised on iOS as you can see on attach, is it needed to change Euro in popup header? We need figma link.
![IMG_1065](https://github.com/sora-xor/sora-card/assets/17094492/664650af-31bf-4a2e-b20c-3af1e2365fe3)

**Comment by spitsynval** [comment]
<img width="417" alt="Снимок экрана 2023-10-16 в 14 32 26" src="https://github.com/sora-xor/sora-card/assets/109540030/e76de8ea-f5b2-4818-86c8-e887158e3aca">

Alright, I fixed wording, according to the problem.

Figma link: https://www.figma.com/file/5kaHWqH73Ekez7RVOpH36g/%E2%9C%85-SORA-Wallet-(on-Prod)?type=design&node-id=13169%3A6620&mode=design&t=K9EMhgHBxoPc9icD-1

P.S.: It's a quick fix, so I did it right in the "On Prod" file. Hope it's ok.
