### ISSUE TITLE
[Tech]: Reworking KYC Status Handling

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card#94]
# Problem

Various issues exist in the current management of different KYC statuses.

# Solution

Implement the correct handling procedures.

# Requirements and Sub-tasks

## Backend

- [x] https://github.com/soramitsu/sora-card-backend/issues/295

## Client Applications

The KYC workflow should be adjusted according to [this diagram](https://www.plantuml.com/plantuml/uml/jLNlZkCq4F-UfnZAbwvqlGVewjZRMq2iJjgLTWK2KTHuxKbZrXa7ssc9r8V7O-UQXXGXJfm_jBBd_sz-CtdlWt2XQqnn_D6ZEnRfNgmVMoGF0XmQt0iA6_BI8H9eWb0ZYBOrMegWBLqNnzlnTYpMpqWgs_xHeO-cmK9fj0yh_IB8bn3bhTKKhelY-478rtYFPZy8KWP7GnPFFUjgoMv0Uy2c3VqLfqAm97jLhEzgbA-UNpO4znzk7y074Jf_NG3e2fRbVGp-d9vA-EeTB6vbq7jSt6GloGd4itwkxI6xaTOvzAqbfMa73NelTiZ-q7Y4PO_-t8HZ-YID-bKnwbn011YIrrwkZ8Ymf4Gdk02Cm01SWWQ0R41mUbU7bCGzITkq1laHAtH84a64m4XvI2hBWmxr00jwCFeLOV7C3KUrU0EBEn5jZ8aNY041WtoR2pneO-050V-KfbEeG5VypYXf1q4t69qshOVMeKI5ILYUthULiytsK6jPRuFTrgcQRJJUViglV9jn8nlOUDfsxj_oblfGSniSXiuHgfkpxkVoCWMYCWiSWlORGhBTheQV7v_04WXu4OQBPFoIs--oV7WUV8wjFPrrWia3uG4-_d87ZEI6-FPq0lkXQrxGPTVS_KofyMIU98h2b5fvjh9bPa_sSCg3K_q9dQu6K3AFuLsYiSIM6pXBVi9CQ74UQng3Zu-5oHgM6KhET2zCnoDbAoW_zdAOe9jfPL8msHTt0mFLOYeUKzcV5R6XUKupbqyONB-uWd_mvrXyqPxFtmSFWjrGchk1U2jfEmhJoPkUrQzVxzZv6oLyZUgtrJSpbVDHdPxPu7vUWCaup8DygtrhH9-9HOc4t2s6HgE_W0flUcYTbOZAGx0PnQmu9pq8iZnGYVSEEnyxjY6EPOsQqVzI4qyxvkhBXVXUQFDb8ppXxoZdLSnRu5YHUmKEXRVa_tTYZepx3spB7mo3LPYbyqYcFqiTrMpSnY-9S0WfELGJfN5x_ojnypuhAuVugTwITrbm7UObDYwbpr_2uycVOh8NF3xOiJA6PceuxEBnDgp7oQBE__dN1ziMxv5KrvY_0000).

### Web

- Design
  - [x] https://github.com/sora-xor/sora-card/issues/101
- Development
  - [x] https://github.com/sora-xor/sora-card-web/issues/34

### Mobile

- Design
  - [x] https://github.com/sora-xor/sora-card/issues/102
- Development
  - [x] https://github.com/sora-xor/sora-card-ios/issues/87
  - [x] https://github.com/sora-xor/sora-card-android/issues/133

**Comment by bgodlin** [comment]
Blocked by https://github.com/sora-xor/sora-card/issues/96

**Comment by 2bogd** [comment]
Example of implementation (web):
![image](https://github.com/sora-xor/sora-card/assets/99387689/4adc3ed6-27b2-43a7-a570-da5e0fa04bdd)

**Comment by Alexey-N-Chernyshov** [comment]
Example of iOS implementation:
```
var userStatus: SCKYCUserStatus {
    // do not use kycStatus, it may be any state:
    // kycStatus == .Successful or kycStatus == completed or kycStatus == failed
    if verificationStatus == .accepted {
        // KYC verification completed, waiting for IBAN
        return .successful
    }

    if kycStatus == .Completed {
        // KYC docs were sent, waiting for KYC verification
        return .pending
    }

    if kycStatus == .Retry {
        // retry
        return .rejected
    }

    if kycStatus == .Started {
        // KYC wasn't completed, reuse reference_number from KYC
        return .userCanceled
    }

    if kycStatus == .Failed {
        // KYC wasn't completed, reuse reference_number from KYC
        return .userCanceled
    }

    if kycStatus == .Rejected {
        // KYC was rejected, start a new one with a new reference_number
        return .rejected
    }
}
```
