### ISSUE TITLE
Phone numbers validation on PW side

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora-card#95]
When inputting your phone number, if you don't add a 0 in front or if you do, it maps to two separate accounts, even though it is the same number

For example, +81-80-XXXX-XXXX and + 81-080-XXXX-XXXX are the same phone number, but they map to two different accounts. The phone numbers should be normalized so they map to the same account.

On both numbers user gets sms code.

**Comment by bgodlin** [comment]
TBD by the partners
