### ISSUE TITLE
[Feature] See rejection reason

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card#98]
## Problem Statement
Currently users are not provided with enough information to determine the reason their KYC application has been rejected.

## Solution
We can receive details from the partner's API. The description received can be shown on the relevant screen.

### Backend

- [x] https://github.com/soramitsu/sora-card-backend/issues/333

### Client applications

The application should present all potential rejection reasons found within the `rejection_reasons ` object, when handling the status according to the newly presented schema in https://github.com/sora-xor/sora-card/issues/94. This object is an array, with each of its child objects containing a `Description` field. It's important to list all of these reasons, so implementing scrolling may be necessary.

#### Web

- Design
  - [x] https://github.com/sora-xor/sora-card/issues/107
- Development
  - [x] https://github.com/sora-xor/sora-card-web/issues/32

#### Mobile

- Design
  - [x] https://github.com/sora-xor/sora-card/issues/108
- Development
  - [x] https://github.com/sora-xor/sora-card-android/issues/130
  - [x] https://github.com/sora-xor/sora-card-ios/issues/85

**Comment by Tieumsan** [comment]
@bgodlin please complete the requirements
@spitsynval please add link to the design

**Comment by bgodlin** [comment]
> please complete the requirements

done

**Comment by Alexey-N-Chernyshov** [comment]
Endpoints `\kyc-status`, `\last-kyc-status`.
Example KYC result with `rejection_reasons`:
```
{
  "kyc_id":"936da01f-9abd-4d9d-80c7-02af85c82222",
  "person_id":"00000000-0000-0000-0000-000000000000",
  "user_reference_number":"1234567890",
  "reference_id":null,
  "kyc_status":"Completed",
  "verification_status":"None",
  "iban_status":"None",
  "card_status":"None",
  "additional_description":"Video verification was rejected",
  "rejection_reasons":[
     {"Description":"The user uploaded screenshots"},
     {"Description":"Your KYC application was rejected"}
  ],
  "update_time":1696494249
}
```

**Comment by 2bogd** [comment]
@bgodlin we need clarity on what to show to users. Current imp shows hardcoded text: `Your application has been rejected.`
So, do we need to use `additional_description` instead of `hardcoded text` and `rejection_reasons`, use all of them, or just ignore `additional_description` ?

**Comment by bgodlin** [comment]
> @bgodlin we need clarity on what to show to users. Current imp shows hardcoded text: `Your application has been rejected.` So, do we need to use `additional_description` instead of `hardcoded text` and `rejection_reasons`, use all of them, or just ignore `additional_description` ?

@2bogd  As it is currently stated in the designs (see https://github.com/sora-xor/sora-card/issues/108#issuecomment-1748746029), you should display both.
